"use client";

import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    "Find Workers": "Find Workers",
    "Post a Job": "Post a Job",
    "Join as Worker": "Join as Worker",
    "Sign In": "Sign In",
    "Home": "Home",
    "About": "About",
    "How It Works": "How It Works",
    "Contact": "Contact",
    "Get Started": "Get Started",
    "Available": "Available",
    "Verified": "Verified",
    "Book Now": "Book Now",
    "Search": "Search",
    "INDIA'S #1 RURAL GIG PLATFORM": "INDIA'S #1 RURAL GIG PLATFORM",
    "Find skilled workers": "Find skilled workers",
    "in your village": "in your village",
    "VillageWork connects skilled rural workers with nearby households and businesses — in their language, at their pace, on WhatsApp.": "VillageWork connects skilled rural workers with nearby households and businesses — in their language, at their pace, on WhatsApp.",
    "I Need a Worker": "I Need a Worker",
    "I Want Work": "I Want Work",
    "10,000+ Workers": "10,000+ Workers",
    "500+ Villages": "500+ Villages",
    "4.8★ Rating": "4.8★ Rating",
    "Ramesh Kumar": "Ramesh Kumar",
    "Electrician": "Electrician",
    "Patna Rural": "Patna Rural",
    "2.3 km": "2.3 km",
    "42 reviews": "42 reviews",
    "Jobs Done": "Jobs Done",
    "Jobs": "Jobs",
    "Rating": "Rating",
    "Response": "Response",
    "< 1hr": "< 1hr",
    "Available Now": "Available Now",
    "/day": "/day",
    "Recent Jobs": "Recent Jobs",
    "Wiring repair": "Wiring repair",
    "Ara Village": "Ara Village",
    "Completed": "Completed",
    "Fan installation": "Fan installation",
    "Chapra": "Chapra",
    "Switchboard fix": "Switchboard fix",
    "Muzaffarpur": "Muzaffarpur",
    "WhatsApp": "WhatsApp",
    "Live Matching": "Live Matching",
    "3 new job requests": "3 new job requests",
    "in Patna Rural today": "in Patna Rural today",
    "Top Rated Worker": "Top Rated Worker",
    "WORKERS ACROSS INDIA": "WORKERS ACROSS INDIA",
    "Priya Sharma": "Priya Sharma",
    "Tutor": "Tutor",
    "Vijay Yadav": "Vijay Yadav",
    "Mason": "Mason",
    "Darbhanga": "Darbhanga",
    "Carpenter": "Carpenter",
    "Anita Kumari": "Anita Kumari",
    "Painter": "Painter",
    "Gaya": "Gaya",
    "Suresh Bind": "Suresh Bind",
    "Nalanda": "Nalanda",
    "Sunita Devi": "Sunita Devi",
    "Tailor": "Tailor",
    "Ara": "Ara",
    "Plumber": "Plumber",
    "Mohan Singh": "Mohan Singh",
    "Raju Mistri": "Raju Mistri",
    "Bhagalpur": "Bhagalpur",
    "Meena Devi": "Meena Devi",
    "Sitamarhi": "Sitamarhi",
    "Gardener": "Gardener",
    "Deepak Kumar": "Deepak Kumar",
    "Vaishali": "Vaishali",
    "Skills for": "Skills for",
    "every village need": "every village need",
    "Find trusted local workers for any job — from repairs to tutoring, in your village, on your terms.": "Find trusted local workers for any job — from repairs to tutoring, in your village, on your terms.",
    "Find skilled workers near you": "Find skilled workers near you",
    "For urgent home repairs, installations, and daily tasks. AI matches you with verified workers within your village or 5km radius — instantly.": "For urgent home repairs, installations, and daily tasks. AI matches you with verified workers within your village or 5km radius — instantly.",
    "Find workers": "Find workers",
    "Post a job in 2 minutes": "Post a job in 2 minutes",
    "For one-time tasks or ongoing work. Describe your need in Hindi or English. Our engine finds the best available match for consistent reliability.": "For one-time tasks or ongoing work. Describe your need in Hindi or English. Our engine finds the best available match for consistent reliability.",
    "Earn from your own village": "Earn from your own village",
    "For skilled workers ready to build a digital reputation. Get verified, receive WhatsApp job alerts, and grow your income without leaving home.": "For skilled workers ready to build a digital reputation. Get verified, receive WhatsApp job alerts, and grow your income without leaving home.",
    "Join as worker": "Join as worker",
    "Tell us the skill you need and when. Add your village name, budget, and preferred date. Done in under 2 minutes — no English required.": "Tell us the skill you need and when. Add your village name, budget, and preferred date. Done in under 2 minutes — no English required.",
    "Get AI-Matched": "Get AI-Matched",
    "Our engine matches you with the top 3 workers by skill, proximity, rating, and availability — instantly. View their profiles before you decide.": "Our engine matches you with the top 3 workers by skill, proximity, rating, and availability — instantly. View their profiles before you decide.",
    "Accept via WhatsApp": "Accept via WhatsApp",
    "Workers get a WhatsApp alert with job details. One tap to accept. Complete the work, earn your pay, and grow your village reputation.": "Workers get a WhatsApp alert with job details. One tap to accept. Complete the work, earn your pay, and grow your village reputation.",
    "VOICES FROM THE VILLAGE": "VOICES FROM THE VILLAGE",
    "Real Workers. Real Stories.": "Real Workers. Real Stories.",
    "VillageWork gave me 3 clients in my first week. I never thought I could find work without going to the city.": "VillageWork gave me 3 clients in my first week. I never thought I could find work without going to the city.",
    "I found a trusted plumber in 10 minutes. The reviews made me feel safe hiring someone I had never met before.": "I found a trusted plumber in 10 minutes. The reviews made me feel safe hiring someone I had never met before.",
    "Homemaker": "Homemaker",
    "My tailoring orders doubled. Now I earn ₹18,000 a month without leaving my village.": "My tailoring orders doubled. Now I earn ₹18,000 a month without leaving my village.",
    "Ready to earn from your village?": "Ready to earn from your village?",
    "Join 10,000+ workers already on VillageWork": "Join 10,000+ workers already on VillageWork",
    "Free": "Free",
    "How it Works": "How it Works",
    "Rural talent Need digital speed.": "Rural talent Need digital speed.",
    "OUR MISSION": "OUR MISSION",
    "We believe every skilled hand deserves a digital identity.": "We believe every skilled hand deserves a digital identity.",
    "Built by a team that grew up in villages and watched talent migrate to cities unnecessarily.": "Built by a team that grew up in villages and watched talent migrate to cities unnecessarily.",
    "Villages Covered": "Villages Covered",
    "Workers Registered": "Workers Registered",
    "Jobs Completed": "Jobs Completed",
    "Average Rating": "Average Rating",
    "WHO WE ARE": "WHO WE ARE",
    "Built for Bharat's": "Built for Bharat's",
    "forgotten workforce": "forgotten workforce",
    "VillageWork was born from a simple observation — India's most skilled workers live in its villages, but its biggest opportunities live in cities. We decided to change that.": "VillageWork was born from a simple observation — India's most skilled workers live in its villages, but its biggest opportunities live in cities. We decided to change that.",
    "We built a hyperlocal platform where an electrician in Bihar can find his first digital client, a tailor in UP can grow a loyal customer base, and a tutor in Bengal can teach without travelling miles — all in their own language, in their own village.": "We built a hyperlocal platform where an electrician in Bihar can find his first digital client, a tailor in UP can grow a loyal customer base, and a tutor in Bengal can teach without travelling miles — all in their own language, in their own village.",
    "No English required": "No English required",
    "Full platform available in Hindi, Bengali, Tamil and more": "Full platform available in Hindi, Bengali, Tamil and more",
    "No app download needed": "No app download needed",
    "Workers receive jobs directly on WhatsApp — zero friction": "Workers receive jobs directly on WhatsApp — zero friction",
    "Government backed": "Government backed",
    "Integrated with Skill India and PM Vishwakarma schemes": "Integrated with Skill India and PM Vishwakarma schemes",
    "Learn Our Story": "Learn Our Story"
  },
  hi: {
    "Find Workers": "काम खोजें",
    "Post a Job": "काम पोस्ट करें",
    "Join as Worker": "वर्कर बनें",
    "Sign In": "साइन इन",
    "Home": "होम",
    "About": "परिचय",
    "How It Works": "कैसे काम करता है",
    "How it Works": "कैसे काम करता है",
    "Contact": "संपर्क",
    "Get Started": "शुरू करें",
    "Available": "उपलब्ध",
    "Verified": "सत्यापित",
    "Book Now": "अभी बुक करें",
    "Search": "खोजें",
    "INDIA'S #1 RURAL GIG PLATFORM": "भारत का #1 ग्रामीण कामगार प्लेटफॉर्म",
    "Find skilled workers": "कुशल कामगार खोजें",
    "in your village": "अपने गाँव में",
    "VillageWork connects skilled rural workers with nearby households and businesses — in their language, at their pace, on WhatsApp.": "VillageWork कुशल ग्रामीण कामगारों को आस-पास के घरों और व्यवसायों से जोड़ता है - उनकी भाषा में, उनकी गति से, WhatsApp पर।",
    "I Need a Worker": "मुझे कामगार चाहिए",
    "I Want Work": "मुझे काम चाहिए",
    "10,000+ Workers": "10,000+ कामगार",
    "500+ Villages": "500+ गाँव",
    "4.8★ Rating": "4.8★ रेटिंग",
    "Ramesh Kumar": "रमेश कुमार",
    "Electrician": "बिजली मिस्त्री",
    "Patna Rural": "पटना ग्रामीण",
    "2.3 km": "2.3 किमी",
    "42 reviews": "42 समीक्षाएं",
    "Jobs Done": "काम पूरे किए",
    "Jobs": "काम",
    "Rating": "रेटिंग",
    "Response": "जवाब का समय",
    "< 1hr": "< 1 घंटा",
    "Available Now": "अभी उपलब्ध",
    "/day": "/दिन",
    "Recent Jobs": "हाल के काम",
    "Wiring repair": "वायरिंग मरम्मत",
    "Ara Village": "आरा गाँव",
    "Completed": "पूरा हुआ",
    "Fan installation": "पंखे की फिटिंग",
    "Chapra": "छपरा",
    "Switchboard fix": "स्विचबोर्ड मरम्मत",
    "Muzaffarpur": "मुजफ्फरपुर",
    "WhatsApp": "WhatsApp",
    "Live Matching": "लाइव मैचिंग",
    "3 new job requests": "3 नए काम के अनुरोध",
    "in Patna Rural today": "आज पटना ग्रामीण में",
    "Top Rated Worker": "टॉप रेटेड कामगार",
    "WORKERS ACROSS INDIA": "पूरे भारत के कामगार",
    "Priya Sharma": "प्रिया शर्मा",
    "Tutor": "ट्यूटर",
    "Vijay Yadav": "विजय यादव",
    "Mason": "राजमिस्त्री",
    "Darbhanga": "दरभंगा",
    "Carpenter": "बढ़ई",
    "Anita Kumari": "अनीता कुमारी",
    "Painter": "पेंटर",
    "Gaya": "गया",
    "Suresh Bind": "सुरेश बिंद",
    "Nalanda": "नालंदा",
    "Sunita Devi": "सुनीता देवी",
    "Tailor": "दर्जी",
    "Ara": "आरा",
    "Plumber": "प्लंबर",
    "Mohan Singh": "मोहन सिंह",
    "Raju Mistri": "राजू मिस्त्री",
    "Bhagalpur": "भागलपुर",
    "Meena Devi": "मीना देवी",
    "Sitamarhi": "सीतामढ़ी",
    "Gardener": "माली",
    "Deepak Kumar": "दीपक कुमार",
    "Vaishali": "वैशाली",
    "Skills for": "कौशल जो",
    "every village need": "हर गाँव की जरूरत पूरी करें",
    "Find trusted local workers for any job — from repairs to tutoring, in your village, on your terms.": "किसी भी काम के लिए भरोसेमंद स्थानीय कामगार खोजें — मरम्मत से लेकर ट्यूशन तक, आपके गाँव में, आपकी शर्तों पर।",
    "Find skilled workers near you": "अपने आस-पास कुशल कामगार खोजें",
    "For urgent home repairs, installations, and daily tasks. AI matches you with verified workers within your village or 5km radius — instantly.": "तत्काल घरेलू मरम्मत, इंस्टॉलेशन और रोजमर्रा के कामों के लिए। एआई आपको तुरंत आपके गाँव या 5 किमी के दायरे में सत्यापित कामगारों से मिलाता है।",
    "Find workers": "कामगार खोजें",
    "Post a job in 2 minutes": "2 मिनट में काम पोस्ट करें",
    "For one-time tasks or ongoing work. Describe your need in Hindi or English. Our engine finds the best available match for consistent reliability.": "एक बार के काम या चल रहे काम के लिए। अपनी जरूरत हिंदी या अंग्रेजी में बताएं। हमारा इंजन विश्वसनीय काम के लिए सबसे अच्छा कामगार खोजता है।",
    "Earn from your own village": "अपने गाँव से ही कमाएं",
    "For skilled workers ready to build a digital reputation. Get verified, receive WhatsApp job alerts, and grow your income without leaving home.": "कुशल कामगारों के लिए जो डिजिटल पहचान बनाने को तैयार हैं। सत्यापित हों, WhatsApp काम के अलर्ट पाएं, और घर छोड़े बिना अपनी आय बढ़ाएं।",
    "Join as worker": "कामगार के रूप में जुड़ें",
    "Tell us the skill you need and when. Add your village name, budget, and preferred date. Done in under 2 minutes — no English required.": "हमें बताएं कि आपको किस कौशल की आवश्यकता है और कब। अपने गाँव का नाम, बजट और पसंदीदा तारीख डालें। 2 मिनट से कम में हो गया — अंग्रेजी की जरूरत नहीं।",
    "Get AI-Matched": "AI से कामगार खोजें",
    "Our engine matches you with the top 3 workers by skill, proximity, rating, and availability — instantly. View their profiles before you decide.": "हमारा इंजन आपको कौशल, दूरी, रेटिंग और उपलब्धता के आधार पर शीर्ष 3 कामगारों से मिलाता है - तुरंत। निर्णय लेने से पहले उनकी प्रोफाइल देखें।",
    "Accept via WhatsApp": "WhatsApp से स्वीकार करें",
    "Workers get a WhatsApp alert with job details. One tap to accept. Complete the work, earn your pay, and grow your village reputation.": "कामगारों को काम के विवरण के साथ WhatsApp अलर्ट मिलता है। स्वीकार करने के लिए एक टैप करें। काम पूरा करें, अपना भुगतान प्राप्त करें, और गाँव में अपनी प्रतिष्ठा बढ़ाएं।",
    "VOICES FROM THE VILLAGE": "गाँव की आवाजें",
    "Real Workers. Real Stories.": "असली कामगार। असली कहानियाँ।",
    "VillageWork gave me 3 clients in my first week. I never thought I could find work without going to the city.": "VillageWork ने मुझे मेरे पहले सप्ताह में 3 ग्राहक दिए। मैंने कभी नहीं सोचा था कि शहर गए बिना काम मिल सकता है।",
    "I found a trusted plumber in 10 minutes. The reviews made me feel safe hiring someone I had never met before.": "मुझे 10 मिनट में एक भरोसेमंद प्लंबर मिल गया। समीक्षाओं ने मुझे किसी ऐसे व्यक्ति को काम पर रखने में सुरक्षित महसूस कराया जिससे मैं पहले कभी नहीं मिली थी।",
    "Homemaker": "गृहिणी",
    "My tailoring orders doubled. Now I earn ₹18,000 a month without leaving my village.": "मेरे सिलाई के ऑर्डर दोगुने हो गए। अब मैं अपना गाँव छोड़े बिना महीने में ₹18,000 कमाती हूँ।",
    "Ready to earn from your village?": "अपने गाँव से कमाने के लिए तैयार हैं?",
    "Join 10,000+ workers already on VillageWork": "VillageWork पर पहले से मौजूद 10,000+ कामगारों में शामिल हों",
    "Free": "मुफ़्त",
    "Rural talent Need digital speed.": "ग्रामीण प्रतिभा को डिजिटल गति की आवश्यकता है।",
    "OUR MISSION": "हमारा मिशन",
    "We believe every skilled hand deserves a digital identity.": "हमारा मानना है कि हर कुशल हाथ एक डिजिटल पहचान का हकदार है।",
    "Built by a team that grew up in villages and watched talent migrate to cities unnecessarily.": "एक ऐसी टीम द्वारा निर्मित जो गाँवों में पली-बढ़ी और प्रतिभा को बिना वजह शहरों की ओर पलायन करते देखा।",
    "Villages Covered": "गाँव शामिल",
    "Workers Registered": "पंजीकृत कामगार",
    "Jobs Completed": "काम पूरे हुए",
    "Average Rating": "औसत रेटिंग",
    "WHO WE ARE": "हम कौन हैं",
    "Built for Bharat's": "भारत के",
    "forgotten workforce": "भूले हुए कार्यबल के लिए निर्मित",
    "VillageWork was born from a simple observation — India's most skilled workers live in its villages, but its biggest opportunities live in cities. We decided to change that.": "विलेजवर्क का जन्म एक सरल अवलोकन से हुआ - भारत के सबसे कुशल कामगार इसके गाँवों में रहते हैं, लेकिन इसके सबसे बड़े अवसर शहरों में हैं। हमने इसे बदलने का फैसला किया।",
    "We built a hyperlocal platform where an electrician in Bihar can find his first digital client, a tailor in UP can grow a loyal customer base, and a tutor in Bengal can teach without travelling miles — all in their own language, in their own village.": "हमने एक हाइपरलोकल प्लेटफॉर्म बनाया है जहाँ बिहार का एक बिजली मिस्त्री अपना पहला डिजिटल ग्राहक पा सकता है, यूपी का एक दर्जी एक वफादार ग्राहक आधार बना सकता है, और बंगाल का एक ट्यूटर मीलों यात्रा किए बिना पढ़ा सकता है - यह सब अपनी भाषा में, अपने ही गाँव में।",
    "No English required": "अंग्रेजी की आवश्यकता नहीं",
    "Full platform available in Hindi, Bengali, Tamil and more": "पूरा प्लेटफॉर्म हिंदी, बंगाली, तमिल और अन्य भाषाओं में उपलब्ध है",
    "No app download needed": "ऐप डाउनलोड करने की कोई आवश्यकता नहीं",
    "Workers receive jobs directly on WhatsApp — zero friction": "कामगारों को सीधे WhatsApp पर काम मिलता है - कोई परेशानी नहीं",
    "Government backed": "सरकार द्वारा समर्थित",
    "Integrated with Skill India and PM Vishwakarma schemes": "स्किल इंडिया और पीएम विश्वकर्मा योजनाओं के साथ एकीकृत",
    "Learn Our Story": "हमारी कहानी जानें"
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const stored = localStorage.getItem('vw_lang');
    if (stored && (stored === 'en' || stored === 'hi')) {
      setLang(stored);
    }
  }, []);

  const toggleLanguage = () => {
    const next = lang === 'en' ? 'hi' : 'en';
    setLang(next);
    localStorage.setItem('vw_lang', next);
  };

  const t = (key) => {
    if (!mounted) return translations.en[key] || key;
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t, mounted }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
